### ISSUE TITLE
`cp -rf app/assets/webpack/*.otf: No such file or directory` error on 1.1.1

### ISSUE THREAD

**Issue by jafffmen** [shakacode/bootstrap-loader#144]
Hi,

While version 1.1.1 is installed, there is a problem with loading `*.otf` files.

```
"node": "5.11.1"
"npm": "3.8.6"
"bootstrap-loader": "1.1.1"
```
 
Server log:
```
> NODE_ENV=production webpack --config webpack.server.rails.build.config.js

Hash: dac9e1db805d4b2f7545
Version: webpack 1.13.2
Time: 11286ms
                               Asset     Size  Chunks             Chunk Names
5399c657acd8426db4cf84f4de4baaa3.png  16.7 kB          [emitted]  
5f3b594bda93772f634e4b5765c26850.png  29.3 kB          [emitted]  
                    server-bundle.js  3.14 MB       0  [emitted]  main
   [0] multi main 52 bytes {0} [built]
 [436] ./img/noimage ^\.\/.*\.png$ 225 bytes {0} [built]
    + 938 hidden modules

(...)

mkdir -p public/assets
cp -rf app/assets/webpack/*.otf app/assets/webpack/*.woff* app/assets/webpack/*.svg app/assets/webpack/*.ttf app/assets/webpack/*.eot* app/assets/webpack/*.png public/assets
cp: app/assets/webpack/*.otf: No such file or directory
rake aborted!
Command failed with status (1): [cp -rf app/assets/webpack/*.otf app/assets...]
/Users/janek/repos/stories-on-walls/lib/tasks/assets.rake:21:in `block (2 levels) in <top (required)>'
/Users/janek/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/janek/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/janek/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile => assets:compile_environment => assets:webpack
(See full trace by running task with --trace)
```

For version 1.1.0 everything is working fine.

Cheers :)

**Comment by AlexKVal** [comment]
Could be related to the regression https://github.com/shakacode/bootstrap-loader/pull/147

**Comment by justin808** [comment]
@jafffmen  Please verify fixed in 1.1.2.

**Comment by jafffmen** [comment]
@justin808 I deleted node_modules directory and bumped to v. 1.1.2 and the problem still exists when precompiling assets.

**Comment by justin808** [comment]
@jafffmen Can you try the older version before 1.1.0 and see if that fixes the issue? 

Looking at your error:

```
cp: app/assets/webpack/*.otf: No such file or directory
rake aborted!
```

it seems the the issue is with the `cp` statement and not bootstrap-loader.

**Comment by jafffmen** [comment]
@justin808 Everything works fine when there is `v. 1.1.0` installed. This problem showed up after update to `v. 1.1.1` or `v. 1.1.2`.

**Comment by justin808** [comment]
I bet this is the issue: https://github.com/shakacode/bootstrap-loader/issues/151

**Comment by justin808** [comment]
Please try 1.1.4 and confirm if this fixes the issue.

**Comment by justin808** [comment]
@jafffmen Any update?

**Comment by jafffmen** [comment]
1.1.4 works perfectly, sorry that it took so long. Issue resolved 👍
