### ISSUE TITLE
ERROR in only one instance of babel-polyfill is allowed  @ ./~/bootstrap-loader/loader.js 1:0-44

### ISSUE THREAD

**Issue by AllenFang** [shakacode/bootstrap-loader#16]
I upgrade <code>bootstrap-loader</code> according #13, and it work for node@0.12.0 and earlier, but I got another problem for <code>babel-polyfill</code> is loaded repeatedly.

the error message is in the following:
```
ERROR in only one instance of babel-polyfill is allowed  @ ./~/bootstrap-loader/loader.js 1:0-44
```
The root cause is I wrote my dev webpack config with es6, and I add <code>require('babel/register');</code> this line in my <code>webpack-dev-server.js</code>

Anyway, if re-write whole webpack config with es5 and it's work, so have any idea to solve it or did I miss something?

Thanks :)

**Comment by strawbrary** [comment]
I was about to create an issue for this. Are you using Babel 5 in your project? v1.0.3 of bootstrap-loader includes the Babel 6 polyfill which will give you that error if your project is also pulling in the Babel 5 polyfill. You could try installing v1.0.1 of bootstrap-loader and see if that fixes it.

**Comment by AllenFang** [comment]
yep,  I'm trying to upgrade to babel 6, but there some troubles I need to solve ;( But to the user of babel 5, your solutions seems like a workaround for now

**Comment by strawbrary** [comment]
I'm in the same boat, still on Babel 5 which is why I was going to create an issue to see if they intended to support projects which haven't upgraded yet.

**Comment by AllenFang** [comment]
:+1:

**Comment by alexfedoseev** [comment]
@AllenFang @strawbrary 
Hey guys, somehow I wasn't subscribed to this repo and missed issue, sorry. I'll take a look at this tomorrow. Guess I can check what version of babel is installed and require it.

**Comment by alexfedoseev** [comment]
Also I'll check node version so `babel-polyfill` will be required only for `node@<=0.12` users.

**Comment by AllenFang** [comment]
@alexfedoseev, it's a bad news for this repo and thanks your helping. Anyway, is there any basic docs or getting started for contributing this repo, I thinks maybe I can do some bug fixing or something like that.

**Comment by justin808** [comment]
@AllenFang I invited you to our slack room! Thanks so much for offering help!

**Comment by alexfedoseev** [comment]
@AllenFang I added [Contributing guide](https://github.com/shakacode/bootstrap-loader/blob/master/CONTRIBUTING.md) with short explanations how things work. Let me know if you want to hack on this issue.

My current plan is:

```js
/* ./src/bootstrap.loader.js */

if (semver.lte(process.version, '0.12.x')) {
  const babelLatest = 'babel-polyfill';
  const babelPrev = 'babel/polyfill';

  const isBabelLatest = require.resolve(babelLatest);
  const isBabelPrev = require.resolve(babelPrev);
  
  if (!isBabelLatest && !isBabelPrev) {
    throw ...
  }

  if (isBabelLatest) {
    require(babelLatest);
  } else {
    require(babelPrev);
  }
}

// imports ...
```

**Comment by AllenFang** [comment]
Thanks your helping, I'll spend some time to study and try my best to contribute this repo

**Comment by alexfedoseev** [comment]
Thanks, @AllenFang!

**Comment by alexfedoseev** [comment]
@AllenFang any updates on this? If you're currently busy, I can handle this issue.

**Comment by AllenFang** [comment]
um.. little busy, i think you can patch this issue if you have free times. sorry

**Comment by alexfedoseev** [comment]
@AllenFang Sure :+1:

**Comment by gpicazo** [comment]
I am also having this issue when trying to use both bootstrap-loader and awesome-typescript-loader.

**Comment by alexfedoseev** [comment]
@AllenFang @strawbrary @gpicazo `1.0.5` is published. Can you confirm that issue is solved?

**Comment by strawbrary** [comment]
@alexfedoseev It's working for me. Thanks!

**Comment by yourmediafriend** [comment]
@alexfedoseev  I am using it with the react-starter-kit and was still showing an issue with regards to babel-polyfill

**Comment by justin808** [comment]
@yourmediafriend What version of node are you using? Any help debugging your situation would be appreciated.

@gpicazo did the latest fix your issue?

**Comment by yourmediafriend** [comment]
@justin808 Turns out I was using an antique version of node. Upgraded to v5.4.1 and everything is working fine. Thanks for pointing me in the right direction.

**Comment by AllenFang** [comment]
@alexfedoseev, finally, I've time to test this issues, but some problem still remain
I use babel 5 and I downgrade nodejs from 4.x to 0.12.0, because my project required.

Then I remove node_modules and install again and run my webpack dev command, but got the following message: 
```
ERROR in Cannot find module 'babel-polyfill'
 @ ./~/bootstrap-loader/loader.js 1:0-44
```

There's a first problem: 
For the user of babel@5, I think  ```babel/polyfill``` is necessary instead of ```babel-polyfill```

However, I just install babel-polyfill@6.3.14 and run again, but got another issues
```
ERROR in only one instance of babel-polyfill is allowed
 @ ./~/bootstrap-loader/loader.js 1:0-44
```

It's the second problem
This problem is same as my first post in this thread, because I wrote my webpack with es6 and run following command to execute
```bash
node --harmony ./webpack/webpack-dev-server.js
```
so I need to add this ```require('babel/register');``` at first line in ```webpack-dev-server.js``` for es6 compatibility. But this will cause a duplicate of babel instance.  

Anyway, I've solved this problem by using ```babel-node``` to run instead of ```node --harmony```,  cause of this solution, I can remove ```require('babel/register');``` to avoid the duplicate of babel instance.

**Comment by alexfedoseev** [comment]
@AllenFang `1.0.6` is published. Please, try it out and close/comment on this issue.

**Comment by AllenFang** [comment]
@alexfedoseev, ok, I will try it !

**Comment by AllenFang** [comment]
@alexfedoseev, please check #29, I think this patch should solve this issues correctly

**Comment by justin808** [comment]
@alexfedoseev Should we merge?
@AllenFang Can you confirm this does affect users of Node 5.5?

**Comment by alexfedoseev** [comment]
@justin808 @AllenFang 

> Can you confirm this does affect users of Node 5.5?
This part shouldn't affect users `>=4.0.0` users, b/c there's no need in polyfill there.
I'll release it later today.

**Comment by AllenFang** [comment]
I've tested it on node@4.1.1 and it's work fine
